name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed for `git rev-list --count` to work properly
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - name: Push Image
        id: push-image
        run: make push-latest

  deploy-stage:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Deployment Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: kustomize-everything/guestbook-deploy
          ref: main
          path: deployment
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push promoted image to deployment repo
        uses: kustomize-everything/action-promote@v3.6.3
        with:
          target-repo: kustomize-everything/guestbook-deploy
          target-branch: main
          working-directory: deployment
          images: |-
            [
              {
                "name": "nginx",
                "newName": "${{ needs.build-image.outputs.image-name }}",
                "newTag": "${{ needs.build-image.outputs.image }}",
                "overlays": ["env/stage"]
              }
            ]
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ssh-key: ${{ secrets.GUESTBOOK_DEPLOY_KEY }}

  deploy-prod:
    needs: [build-image, deploy-stage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Deployment Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: kustomize-everything/guestbook-deploy
          ref: main
          path: deployment
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push promoted image to deployment repo
        uses: kustomize-everything/action-promote@v3.6.3
        with:
          target-repo: kustomize-everything/guestbook-deploy
          target-branch: main
          working-directory: deployment
          images: |-
            [
              {
                "name": "nginx",
                "newName": "${{ needs.build-image.outputs.image-name }}",
                "newTag": "${{ needs.build-image.outputs.image }}",
                "overlays": ["env/prod"]
              }
            ]
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ssh-key: ${{ secrets.GUESTBOOK_DEPLOY_KEY }}
