name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed for `git rev-list --count` to work properly
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - name: Push Image
        id: push-image
        run: make push-latest

  deploy-stage:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Push promoted image to deployment repo
        uses: kustomize-everything/action-promote@v1.0.1
        with:
          target-repo: kustomize-everything/guestbook-deploy
          target-branch: main
          target-dir: env/stage
          working-directory: guestbook-deploy
          image-name-tag: ${{ needs.build-image.outputs.image }}
          ssh-key: ${{ secrets.GUESTBOOK_DEPLOY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    needs: [build-image, deploy-stage]
    runs-on: ubuntu-latest
    steps:
      - name: Push promoted image to deployment repo
        uses: kustomize-everything/action-promote@v1.0.1
        with:
          target-repo: kustomize-everything/guestbook-deploy
          target-branch: main
          target-dir: env/prod
          working-directory: guestbook-deploy
          image-name-tag: ${{ needs.build-image.outputs.image }}
          ssh-key: ${{ secrets.GUESTBOOK_DEPLOY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
